export { default as Navigation } from "./nav";
export { default as Footer } from "./foot";
export { default as Home } from "./home";
export { default as Ooo } from "./ooo";
export { default as Profile } from "./profile";
export { default as Forum } from "./forum";
export { default as Oooslug } from "./oooslug";
export { default as ProfileSlug } from "./profileslug";
export { default as Mint } from "./mint";